In [ ]:
# Mutual Fund Analytics - Exploratory Data Analysis (EDA)

## Author : Vansh Rawat

## Objective : This notebook performs exploratory data analysis on the Mutual Fund Analytics dataset.
# The analysis covers NAV trends, AUM growth, SIP inflows, investor demographics, portfolio allocation,
# benchmark performance, and other industry insights using Python visualization libraries.

### Libraries Used : Pandas, Numpy, Matplotlib, Seaborn, Plotly.

In [3]:
#Imports!!!
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import plotly.express as px
import plotly.graph_objects as go

from pathlib import Path

# Styling
sns.set_theme(style="whitegrid")
plt.rcParams["figure.figsize"] = (12,6)

In [4]:
DATA_PATH = Path("../Data/Processed")

fund_metadata = pd.read_csv(DATA_PATH/"fund_metadata.csv")

nav_history = pd.read_csv(DATA_PATH/"nav_history.csv")

aum = pd.read_csv(DATA_PATH/"03_aum_by_fund_house.csv")

sip = pd.read_csv(DATA_PATH/"04_monthly_sip_inflows.csv")

category = pd.read_csv(DATA_PATH/"05_category_inflows.csv")

folio = pd.read_csv(DATA_PATH/"06_industry_folio_count.csv")

scheme = pd.read_csv(DATA_PATH/"07_scheme_performance.csv")

investor = pd.read_csv(DATA_PATH/"08_investor_transactions.csv")

portfolio = pd.read_csv(DATA_PATH/"09_portfolio_holdings.csv")

benchmark = pd.read_csv(DATA_PATH/"10_benchmark_indices.csv")

In [5]:
datasets = {
    "Fund Metadata": fund_metadata,
    "NAV History": nav_history,
    "AUM": aum,
    "SIP": sip,
    "Category": category,
    "Folio": folio,
    "Scheme": scheme,
    "Investor": investor,
    "Portfolio": portfolio,
    "Benchmark": benchmark
}

for name, df in datasets.items():
    print(f"{name:<25} {df.shape}")

Fund Metadata             (5, 7)
NAV History               (16911, 3)
AUM                       (90, 5)
SIP                       (48, 6)
Category                  (144, 3)
Folio                     (21, 6)
Scheme                    (40, 19)
Investor                  (32778, 13)
Portfolio                 (322, 8)
Benchmark                 (8050, 3)

In [6]:
for name, df in datasets.items():

    print("="*60)
    print(name)
    print("="*60)

    display(df.head())

    print(df.info())

    print(df.describe(include="all"))

    print()

============================================================
Fund Metadata
============================================================

,fund_house,scheme_type,scheme_category,scheme_code,scheme_name,isin_growth,isin_div_reinvestment
0,Aditya Birla Sun Life Mutual Fund,Open Ended Schemes,Debt Scheme - Banking and PSU Fund,119551,Aditya Birla Sun Life Banking & PSU Debt Fund ...,INF209KA12Z1,INF209KA13Z9
1,Axis Mutual Fund,Open Ended Schemes,Equity Scheme - ELSS,120503,Axis ELSS Tax Saver Fund - Direct Plan - Growt...,INF846K01EW2,NaN
2,Nippon India Mutual Fund,Open Ended Schemes,Equity Scheme - Large Cap Fund,118632,Nippon India Large Cap Fund - Direct Plan Grow...,INF204K01XI3,NaN
3,HDFC Mutual Fund,Open Ended Schemes,Debt Scheme - Money Market Fund,119092,HDFC Money Market Fund - Growth Option - Direc...,INF179KB1HU9,NaN
4,quant Mutual Fund,Open Ended Schemes,Equity Scheme - Mid Cap Fund,120841,quant Mid Cap Fund - Growth Option - Direct Plan,INF966L01887,NaN

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   fund_house             5 non-null      str
 1   scheme_type            5 non-null      str
 2   scheme_category        5 non-null      str
 3   scheme_code            5 non-null      int64
 4   scheme_name            5 non-null      str
 5   isin_growth            5 non-null      str
 6   isin_div_reinvestment  1 non-null      str
dtypes: int64(1), str(6)
memory usage: 412.0 bytes
None
                               fund_house         scheme_type  \
count                                   5                   5
unique                                  5                   1
top     Aditya Birla Sun Life Mutual Fund  Open Ended Schemes
freq                                    1                   5
mean                                  NaN                 NaN
std                                   NaN                 NaN
min                                   NaN                 NaN
25%                                   NaN                 NaN
50%                                   NaN                 NaN
75%                                   NaN                 NaN
max                                   NaN                 NaN

                           scheme_category    scheme_code  \
count                                    5       5.000000
unique                                   5            NaN
top     Debt Scheme - Banking and PSU Fund            NaN
freq                                     1            NaN
mean                                   NaN  119723.800000
std                                    NaN     932.248197
min                                    NaN  118632.000000
25%                                    NaN  119092.000000
50%                                    NaN  119551.000000
75%                                    NaN  120503.000000
max                                    NaN  120841.000000

                                              scheme_name   isin_growth  \
count                                                   5             5
unique                                                  5             5
top     Aditya Birla Sun Life Banking & PSU Debt Fund ...  INF209KA12Z1
freq                                                    1             1
mean                                                  NaN           NaN
std                                                   NaN           NaN
min                                                   NaN           NaN
25%                                                   NaN           NaN
50%                                                   NaN           NaN
75%                                                   NaN           NaN
max                                                   NaN           NaN

       isin_div_reinvestment
count                      1
unique                     1
top             INF209KA13Z9
freq                       1
mean                     NaN
std                      NaN
min                      NaN
25%                      NaN
50%                      NaN
75%                      NaN
max                      NaN

============================================================
NAV History
============================================================

         date      nav  scheme_code
0  2013-01-02  14.6967       118632
1  2013-01-03  14.7305       118632
2  2013-01-04  14.8037       118632
3  2013-01-07  14.7718       118632
4  2013-01-08  14.7197       118632

<class 'pandas.DataFrame'>
RangeIndex: 16911 entries, 0 to 16910
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         16911 non-null  str
 1   nav          16911 non-null  float64
 2   scheme_code  16911 non-null  int64
dtypes: float64(1), int64(1), str(1)
memory usage: 396.5 KB
None
              date           nav    scheme_code
count        16911  16911.000000   16911.000000
unique        3661           NaN            NaN
top     2013-01-07           NaN            NaN
freq             5           NaN            NaN
mean           NaN    795.321029  119715.025132
std            NaN   1648.798011     832.498853
min            NaN     12.219100  118632.000000
25%            NaN     38.258250  119092.000000
50%            NaN     91.922000  119551.000000
75%            NaN    148.545950  120503.000000
max            NaN   6248.798500  120841.000000

============================================================
AUM
============================================================

         date           fund_house  aum_lakh_crore  aum_crore  num_schemes
0  2022-03-31      SBI Mutual Fund            6.05     605000          186
1  2022-03-31  ICICI Prudential MF            4.65     465000          216
2  2022-03-31     HDFC Mutual Fund            4.35     435000          195
3  2022-03-31      Nippon India MF            2.70     270000          177
4  2022-03-31    Kotak Mahindra MF            2.70     270000          168

<class 'pandas.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            90 non-null     str
 1   fund_house      90 non-null     str
 2   aum_lakh_crore  90 non-null     float64
 3   aum_crore       90 non-null     int64
 4   num_schemes     90 non-null     int64
dtypes: float64(1), int64(2), str(2)
memory usage: 3.6 KB
None
              date       fund_house  aum_lakh_crore     aum_crore  num_schemes
count           90               90       90.000000  9.000000e+01    90.000000
unique           9               10             NaN           NaN          NaN
top     2022-03-31  SBI Mutual Fund             NaN           NaN          NaN
freq            10                9             NaN           NaN          NaN
mean           NaN              NaN        4.352889  4.352889e+05   152.200000
std            NaN              NaN        2.734328  2.734328e+05    52.108832
min            NaN              NaN        1.050000  1.050000e+05    56.000000
25%            NaN              NaN        2.525000  2.525000e+05    95.000000
50%            NaN              NaN        3.450000  3.450000e+05   172.500000
75%            NaN              NaN        5.675000  5.675000e+05   195.000000
max            NaN              NaN       12.500000  1.250000e+06   216.000000

============================================================
SIP
============================================================

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
0,1640995200000000,11517,4.91,9.10,4.80,NaN
1,1643673600000000,11438,4.93,8.20,4.85,NaN
2,1646092800000000,12328,5.09,10.50,5.01,NaN
3,1648771200000000,11863,5.48,9.52,5.12,NaN
4,1651363200000000,12286,5.55,8.10,5.15,NaN

<class 'pandas.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   month                      48 non-null     int64
 1   sip_inflow_crore           48 non-null     int64
 2   active_sip_accounts_crore  48 non-null     float64
 3   new_sip_accounts_lakh      48 non-null     float64
 4   sip_aum_lakh_crore         48 non-null     float64
 5   yoy_growth_pct             36 non-null     float64
dtypes: float64(4), int64(2)
memory usage: 2.4 KB
None
              month  sip_inflow_crore  active_sip_accounts_crore  \
count  4.800000e+01         48.000000                  48.000000
mean   1.702724e+15      19577.520833                   7.189583
std    3.682982e+13       6354.329621                   1.271457
min    1.640995e+15      11438.000000                   4.910000
25%    1.671862e+15      13658.500000                   6.110000
50%    1.702728e+15      18224.000000                   7.150000
75%    1.733681e+15      25944.250000                   8.300000
max    1.764547e+15      31002.000000                   9.350000

       new_sip_accounts_lakh  sip_aum_lakh_crore  yoy_growth_pct
count              48.000000           48.000000       36.000000
mean                9.893750            8.632083       31.456944
std                 5.370745            3.613579       11.768190
min                 7.500000            4.800000       15.800000
25%                 8.775000            5.790000       20.245000
50%                 9.200000            7.265000       28.295000
75%                 9.562500           10.525000       40.807500
max                46.000000           15.900000       53.050000

============================================================
Category
============================================================

        month         category  net_inflow_crore
0  2024-04-01        Large Cap            2413.0
1  2024-04-01          Mid Cap            3897.0
2  2024-04-01        Small Cap            3533.0
3  2024-04-01        Flexi Cap            4947.0
4  2024-04-01  Large & Mid Cap            4214.0

<class 'pandas.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   month             144 non-null    str
 1   category          144 non-null    str
 2   net_inflow_crore  144 non-null    float64
dtypes: float64(1), str(2)
memory usage: 3.5 KB
None
             month   category  net_inflow_crore
count          144        144        144.000000
unique          12         12               NaN
top     2024-04-01  Large Cap               NaN
freq            12         12               NaN
mean           NaN        NaN       6473.881944
std            NaN        NaN       9718.335947
min            NaN        NaN        437.000000
25%            NaN        NaN       1801.250000
50%            NaN        NaN       4148.000000
75%            NaN        NaN       5304.000000
max            NaN        NaN      41952.000000

============================================================
Folio
============================================================

,month,total_folios_crore,equity_folios_crore,debt_folios_crore,hybrid_folios_crore,others_folios_crore
0,NaN,13.26,9.28,1.86,0.80,1.33
1,NaN,13.91,9.74,1.95,0.83,1.39
2,NaN,13.85,9.69,1.94,0.83,1.38
3,NaN,14.12,9.88,1.98,0.85,1.41
4,NaN,14.81,10.37,2.07,0.89,1.48

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   month                0 non-null      float64
 1   total_folios_crore   21 non-null     float64
 2   equity_folios_crore  21 non-null     float64
 3   debt_folios_crore    21 non-null     float64
 4   hybrid_folios_crore  21 non-null     float64
 5   others_folios_crore  21 non-null     float64
dtypes: float64(6)
memory usage: 1.1 KB
None
       month  total_folios_crore  equity_folios_crore  debt_folios_crore  \
count    0.0           21.000000            21.000000          21.000000
mean     NaN           19.829524            13.880476           2.776190
std      NaN            4.583376             3.207799           0.640308
min      NaN           13.260000             9.280000           1.860000
25%      NaN           15.540000            10.880000           2.180000
50%      NaN           19.980000            13.990000           2.800000
75%      NaN           23.890000            16.720000           3.340000
max      NaN           26.120000            18.280000           3.660000

       hybrid_folios_crore  others_folios_crore
count            21.000000            21.000000
mean              1.190000             1.983333
std               0.274864             0.459079
min               0.800000             1.330000
25%               0.930000             1.550000
50%               1.200000             2.000000
75%               1.430000             2.390000
max               1.570000             2.610000

============================================================
Scheme
============================================================

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,NaN,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,NaN
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,NaN,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,NaN
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,NaN,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,NaN
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,NaN,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,NaN
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,NaN,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,NaN

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   scheme_name         40 non-null     str
 2   fund_house          40 non-null     str
 3   category            40 non-null     str
 4   plan                0 non-null      float64
 5   return_1yr_pct      40 non-null     float64
 6   return_3yr_pct      40 non-null     float64
 7   return_5yr_pct      40 non-null     float64
 8   benchmark_3yr_pct   40 non-null     float64
 9   alpha               40 non-null     float64
 10  beta                40 non-null     float64
 11  sharpe_ratio        40 non-null     float64
 12  sortino_ratio       40 non-null     float64
 13  std_dev_ann_pct     40 non-null     float64
 14  max_drawdown_pct    40 non-null     float64
 15  aum_crore           40 non-null     int64
 16  expense_ratio_pct   40 non-null     float64
 17  morningstar_rating  40 non-null     int64
 18  risk_grade          0 non-null      float64
dtypes: float64(13), int64(3), str(3)
memory usage: 6.1 KB
None
            amfi_code                                scheme_name  \
count       40.000000                                         40
unique            NaN                                         40
top               NaN  SBI Bluechip Fund - Regular Plan - Growth
freq              NaN                                          1
mean    120247.000000                                        NaN
std      14534.998667                                        NaN
min     100016.000000                                        NaN
25%     118632.750000                                        NaN
50%     119551.500000                                        NaN
75%     120842.250000                                        NaN
max     149324.000000                                        NaN

             fund_house   category  plan  return_1yr_pct  return_3yr_pct  \
count                40         40   0.0       40.000000       40.000000
unique               10         12   NaN             NaN             NaN
top     SBI Mutual Fund  Large Cap   NaN             NaN             NaN
freq                  5         14   NaN             NaN             NaN
mean                NaN        NaN   NaN       14.376000       14.089000
std                 NaN        NaN   NaN        4.883023        4.617253
min                 NaN        NaN   NaN        4.260000        5.140000
25%                 NaN        NaN   NaN       11.735000       12.035000
50%                 NaN        NaN   NaN       14.620000       14.205000
75%                 NaN        NaN   NaN       16.392500       15.882500
max                 NaN        NaN   NaN       24.930000       23.390000

        return_5yr_pct  benchmark_3yr_pct      alpha       beta  sharpe_ratio  \
count        40.000000          40.000000  40.000000  40.000000     40.000000
unique             NaN                NaN        NaN        NaN           NaN
top                NaN                NaN        NaN        NaN           NaN
freq               NaN                NaN        NaN        NaN           NaN
mean         14.516750          12.835500   1.253500   0.873250      1.361750
std           4.454021           4.740972   0.447412   0.224846      1.475805
min           5.430000           3.960000   0.510000   0.220000      0.800000
25%          12.340000          10.690000   0.887500   0.890000      0.865000
50%          14.185000          13.090000   1.205000   0.960000      0.925000
75%          17.585000          14.775000   1.700000   1.000000      0.985000
max          23.800000          22.160000   1.980000   1.040000      7.680000

        sortino_ratio  std_dev_ann_pct  max_drawdown_pct    aum_crore  \
count       40.000000        40.000000         40.000000     40.00000
unique            NaN              NaN               NaN          NaN
top               NaN              NaN               NaN          NaN
freq              NaN              NaN               NaN          NaN
mean         2.082500        14.962500        -19.200250  26091.60000
std          2.203144         6.669282          8.819164  13809.11134
min          1.030000         0.500000        -33.500000    979.00000
25%          1.270000        14.000000        -25.062500  17400.50000
50%          1.445000        14.000000        -20.600000  26713.00000
75%          1.637500        19.000000        -14.255000  38125.00000
max         10.370000        25.000000         -2.230000  49046.00000

        expense_ratio_pct  morningstar_rating  risk_grade
count           40.000000           40.000000         0.0
unique                NaN                 NaN         NaN
top                   NaN                 NaN         NaN
freq                  NaN                 NaN         NaN
mean             1.237000            4.250000         NaN
std              0.386584            0.742484         NaN
min              0.550000            3.000000         NaN
25%              0.787500            4.000000         NaN
50%              1.425000            4.000000         NaN
75%              1.540000            5.000000         NaN
max              1.640000            5.000000         NaN

============================================================
Investor
============================================================

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

<class 'pandas.DataFrame'>
RangeIndex: 32778 entries, 0 to 32777
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   investor_id         32778 non-null  str
 1   transaction_date    13048 non-null  str
 2   amfi_code           32778 non-null  int64
 3   transaction_type    32778 non-null  str
 4   amount_inr          32778 non-null  int64
 5   state               32778 non-null  str
 6   city                32778 non-null  str
 7   city_tier           32778 non-null  str
 8   age_group           32778 non-null  str
 9   gender              32778 non-null  str
 10  annual_income_lakh  32778 non-null  float64
 11  payment_mode        32778 non-null  str
 12  kyc_status          32778 non-null  str
dtypes: float64(1), int64(2), str(10)
memory usage: 3.3 MB
None
       investor_id transaction_date      amfi_code transaction_type  \
count        32778            13048   32778.000000            32778
unique        5000              204            NaN                3
top      INV001497       2024-12-06            NaN              SIP
freq            12               86            NaN            19716
mean           NaN              NaN  120264.617518              NaN
std            NaN              NaN   14370.205345              NaN
min            NaN              NaN  100016.000000              NaN
25%            NaN              NaN  118632.000000              NaN
50%            NaN              NaN  119551.000000              NaN
75%            NaN              NaN  120843.000000              NaN
max            NaN              NaN  149324.000000              NaN

           amount_inr   state     city city_tier age_group gender  \
count    32778.000000   32778    32778     32778     32778  32778
unique            NaN      12       24         2         5      2
top               NaN  Punjab  Kolkata       T30     26-35   Male
freq              NaN    2965     2748     21719     13463  21809
mean    107437.318628     NaN      NaN       NaN       NaN    NaN
std     150415.905084     NaN      NaN       NaN       NaN    NaN
min        400.000000     NaN      NaN       NaN       NaN    NaN
25%       3153.000000     NaN      NaN       NaN       NaN    NaN
50%      17782.500000     NaN      NaN       NaN       NaN    NaN
75%     189324.250000     NaN      NaN       NaN       NaN    NaN
max     597498.000000     NaN      NaN       NaN       NaN    NaN

        annual_income_lakh payment_mode kyc_status
count         32778.000000        32778      32778
unique                 NaN            4          2
top                    NaN  Net Banking   Verified
freq                   NaN         8250      30146
mean             26.181219          NaN        NaN
std              20.805425          NaN        NaN
min               3.000000          NaN        NaN
25%              10.600000          NaN        NaN
50%              19.700000          NaN        NaN
75%              37.400000          NaN        NaN
max              99.700000          NaN        NaN

============================================================
Portfolio
============================================================

,amfi_code,stock_symbol,stock_name,sector,weight_pct,market_value_cr,current_price_inr,portfolio_date
0,119551,POWERGRID,Power Grid Corporation,Utilities,13.85,737.09,6011.08,2025-12-31
1,119551,HDFCBANK,HDFC Bank Ltd,Banking,11.19,88.97,1074.65,2025-12-31
2,119551,GRASIM,Grasim Industries Ltd,Diversified,9.90,208.45,5964.59,2025-12-31
3,119551,DRREDDY,Dr. Reddy's Laboratories,Pharma,4.76,161.32,3748.82,2025-12-31
4,119551,ASIANPAINT,Asian Paints Ltd,Paints,10.25,725.90,1321.45,2025-12-31

<class 'pandas.DataFrame'>
RangeIndex: 322 entries, 0 to 321
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   amfi_code          322 non-null    int64
 1   stock_symbol       322 non-null    str
 2   stock_name         322 non-null    str
 3   sector             322 non-null    str
 4   weight_pct         322 non-null    float64
 5   market_value_cr    322 non-null    float64
 6   current_price_inr  322 non-null    float64
 7   portfolio_date     322 non-null    str
dtypes: float64(3), int64(1), str(4)
memory usage: 20.3 KB
None
            amfi_code stock_symbol         stock_name   sector  weight_pct  \
count      322.000000          322                322      322  322.000000
unique            NaN           30                 30       14         NaN
top               NaN   BHARTIARTL  Bharti Airtel Ltd  Banking         NaN
freq              NaN           15                 15       60         NaN
mean    121210.434783          NaN                NaN      NaN   10.558975
std      14669.377920          NaN                NaN      NaN    6.060137
min     100016.000000          NaN                NaN      NaN    0.990000
25%     118633.000000          NaN                NaN      NaN    6.015000
50%     119552.000000          NaN                NaN      NaN    9.395000
75%     120842.750000          NaN                NaN      NaN   13.917500
max     149324.000000          NaN                NaN      NaN   38.180000

        market_value_cr  current_price_inr portfolio_date
count        322.000000         322.000000            322
unique              NaN                NaN              1
top                 NaN                NaN     2025-12-31
freq                NaN                NaN            322
mean        1008.846646        4080.870528            NaN
std          543.827535        2265.186353            NaN
min           55.740000         246.780000            NaN
25%          513.702500        2081.985000            NaN
50%         1045.670000        4138.995000            NaN
75%         1477.502500        5914.307500            NaN
max         1999.500000        7942.960000            NaN

============================================================
Benchmark
============================================================

         date index_name  close_value
0  2022-03-01    NIFTY50     17492.79
1  2022-04-01    NIFTY50     17689.64
2  2022-05-01    NIFTY50     17835.05
3  2022-06-01    NIFTY50     17878.51
4  2022-07-01    NIFTY50     17759.15

<class 'pandas.DataFrame'>
RangeIndex: 8050 entries, 0 to 8049
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         3171 non-null   str
 1   index_name   8050 non-null   str
 2   close_value  8050 non-null   float64
dtypes: float64(1), str(2)
memory usage: 188.8 KB
None
              date index_name   close_value
count         3171       8050   8050.000000
unique         453          7           NaN
top     2022-03-01    NIFTY50           NaN
freq             7       1150           NaN
mean           NaN        NaN  18351.950181
std            NaN        NaN  14169.995121
min            NaN        NaN   1444.130000
25%            NaN        NaN   2819.062500
50%            NaN        NaN  18392.960000
75%            NaN        NaN  26539.097500
max            NaN        NaN  79075.390000

In [7]:
missing = pd.DataFrame({
    "Missing Values": [
        df.isnull().sum().sum()
        for df in datasets.values()
    ]
}, index=datasets.keys())

missing

               Missing Values
Fund Metadata               4
NAV History                 0
AUM                         0
SIP                        12
Category                    0
Folio                      21
Scheme                     80
Investor                19730
Portfolio                   0
Benchmark                4879

In [8]:
duplicates = pd.DataFrame({
    "Duplicate Rows":[
        df.duplicated().sum()
        for df in datasets.values()
    ]
}, index=datasets.keys())

duplicates

               Duplicate Rows
Fund Metadata               0
NAV History                 0
AUM                         0
SIP                         0
Category                    0
Folio                       0
Scheme                      0
Investor                    0
Portfolio                   0
Benchmark                  12

In [ ]:
## Initial Observations : 
# Successfully loaded all processed datasets.
# Verified data quality after preprocessing.
# No critical missing values affecting analysis.
# Data is ready for visualization and exploratory analysis.